pipeline {
   agent any
   environment {
       CLUSTER_NAME = "elhasbi-cluster"
       REGION = "us-east-1"
   }
   stages {
       stage('Create EKS Cluster') {
           steps {
               withCredentials([[ 
                   $class: 'AmazonWebServicesCredentialsBinding',
                   credentialsId: "awscredss", 
                   accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                   secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
               ]]) {
                   sh '''
                       eksctl create cluster \
                       --name ${CLUSTER_NAME} \
                       --region ${REGION} \
                       --node-type t2.micro \
                       --nodes 2 \
                       --nodes-min 1 \
                       --nodes-max 2 \
                       --managed
                   '''
               }
           }
       }
       stage('Deploy App') {
           steps {
               withCredentials([[ 
                   $class: 'AmazonWebServicesCredentialsBinding', 
                   credentialsId: "awscredss", 
                   accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
                   secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
               ]]) {
                   script {
                       sh "aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${REGION}"
                       
                       sh """
                       cd minikube
                       kubectl apply -f deployment.yml
                       kubectl apply -f service.yml
                       kubectl get services
                       """
                       
                       sleep(time: 30, unit: "SECONDS")
                   }
               }
           }
       }
   }
   post {
       always {
           echo 'Cleaning up...'
       }
   }
}
