pipeline {
    agent any

    parameters {
        string(name: 'DEPLOYMENT', defaultValue: 'default-deployment', description: 'Name of the deployment to apply')
    }

    stages {
        stage('Check Minikube Status') {
            steps {
                script {
                    // Check Minikube status
                    def status = sh(script: 'minikube status', returnStatus: true)
                    if (status != 0) {
                        echo "Minikube is not running. Starting Minikube..."
                        sh 'minikube start'
                    } else {
                        echo "Minikube is running."
                    }
                }
            }
        }

        stage('Deploy App') {
            steps {
                script {
                    // Apply the Kubernetes configurations
                    sh """
                    cd minikube
                    kubectl apply -f deployment.yml 
                    kubectl apply -f service.yml 
                    """
                    sleep(time: 50, unit: "SECONDS")  // Wait for resources to be applied
                }
            }
        }

        stage('Get App URL') {
            steps {
                script {
                    // Get the service URL from Minikube
                    def serviceURL = sh(script: 'minikube service morocco-service --url', returnStdout: true).trim()

                    // Print the service URL
                    echo "The application is accessible at: ${serviceURL}"
                }
            }
        }
    }
}
